Func GoOutCaravanMaguuma_TalmarkWilderness()
        _Vanquisher_RunDynamicCaravanGoOut($TalmarkWilderness_Map, "TalmarkWilderness")
EndFunc

Func VQCaravanMaguuma_TalmarkWilderness()
        If _Vanquisher_IsCombinedMaguumaCaravanActive() Then
                If GetMapID() <> $TalmarkWilderness_Map Then
                        _Vanquisher_ApplyDifficulty()
                        GoOutCaravanMaguuma_TalmarkWilderness()
                        If GetMapID() <> $TalmarkWilderness_Map Then
                                CurrentAction("Routing - on map " & GetMapID() & ", need TalmarkWilderness (" & $TalmarkWilderness_Map & ").")
                                Return
                        EndIf
                EndIf
        Else
                If GetMapID() <> $TalmarkWilderness_Map And GetMapID() <> $TalmarkWilderness_Outpost And GetMapID() <> $TalmarkWilderness_Transit Then
                        _Vanquisher_ResetGoOutRouteProgress()
                        CurrentAction("Traveling to outpost for TalmarkWilderness.")
                        TravelTo($TalmarkWilderness_Outpost)
                EndIf

                If GetMapID() = $TalmarkWilderness_Outpost Or GetMapID() = $TalmarkWilderness_Transit Then
                        _Vanquisher_ApplyDifficulty()
                        GoOutCaravanMaguuma_TalmarkWilderness()
                        If GetMapID() <> $TalmarkWilderness_Map Then
                                CurrentAction("Routing - on map " & GetMapID() & ", need TalmarkWilderness (" & $TalmarkWilderness_Map & ").")
                                Return
                        EndIf
                EndIf
        EndIf

	If GetMapID() <> $TalmarkWilderness_Map Then
		CurrentAction("TalmarkWilderness route waiting - on map " & GetMapID() & ", need " & $TalmarkWilderness_Map & ".")
		Return
	EndIf

	CurrentAction("Starting TalmarkWilderness vanquish route.")


	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(16888, 2685)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(10801, 8084)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(8472, 8084)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(9795, 11948)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(7836, 5755)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(3125, 8031)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-1692, 7396)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-4021, 9672)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-7038, 10678)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-4127, 16024)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-421, 12583)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(4872, 14489)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-377, 12410)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-5391, 13832)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-6983, 10716)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-8643, 9801)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-10608, 13765)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-12979, 13460)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-13352, 10784)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-16299, 9564)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-16807, 7464)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-18603, 4686)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-16977, 7362)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-14233, 10750)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-12200, 9225)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-9591, 8514)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-10438, 3466)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-12225, 188)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-10828, -2522)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-6974, -5401)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-4264, -4089)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-1935, -2437)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-1709, -6498)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-555, -4552)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-72, -2098)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-2740, 824)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-6726, 1964)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-2909, 2136)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-2824, 5355)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(267, 6159)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(606, -108)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(4849, 1524)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(6831, 4338)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(11150, 2856)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(11955, -447)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(12600, -4097)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(10633, -3261)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(7254, -1675)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(2808, -1506)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(6407, -3792)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(4713, -6714)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(8059, -8662)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(10049, -9086)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(10388, -9170)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(13691, -10102)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(13288, -7637)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(11813, -7490)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(13860, -9933)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(10134, -9382)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(12505, -13659)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(7466, -10144)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(6915, -12092)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(6661, -15353)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(9071, -15697)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(3104, -14464)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(5349, -10652)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(5052, -8154)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(2723, -7730)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(2850, -10017)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-538, -11584)

	; reverse
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-538, -11584)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(2850, -10017)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(2723, -7730)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(5052, -8154)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(5349, -10652)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(3104, -14464)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(9071, -15697)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(6661, -15353)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(6915, -12092)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(7466, -10144)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(12505, -13659)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(10134, -9382)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(13860, -9933)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(11813, -7490)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(13288, -7637)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(13691, -10102)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(10388, -9170)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(10049, -9086)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(8059, -8662)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(4713, -6714)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(6407, -3792)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(2808, -1506)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(7254, -1675)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(10633, -3261)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(12600, -4097)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(11955, -447)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(11150, 2856)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(6831, 4338)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(4849, 1524)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(606, -108)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(267, 6159)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-2824, 5355)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-2909, 2136)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-6726, 1964)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-2740, 824)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-72, -2098)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-555, -4552)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-1709, -6498)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-1935, -2437)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-4264, -4089)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-6974, -5401)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-10828, -2522)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-12225, 188)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-10438, 3466)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-9591, 8514)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-12200, 9225)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-14233, 10750)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-16977, 7362)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-18603, 4686)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-16807, 7464)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-16299, 9564)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-13352, 10784)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-12979, 13460)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-10608, 13765)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-8643, 9801)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-6983, 10716)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-5391, 13832)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-377, 12410)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(4872, 14489)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-421, 12583)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-4127, 16024)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-7038, 10678)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-4021, 9672)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-1692, 7396)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(3125, 8031)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(7836, 5755)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(9795, 11948)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(8472, 8084)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(10801, 8084)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(16888, 2685)
EndFunc
