Func GoOutCaravanMaguuma_MajestysRest()
        _Vanquisher_RunDynamicCaravanGoOut($MajestysRest_Map, "MajestysRest")
EndFunc

Func VQCaravanMaguuma_MajestysRest()
       If _Vanquisher_IsCombinedMaguumaCaravanActive() Then
               If GetMapID() <> $MajestysRest_Map Then
                       _Vanquisher_ApplyDifficulty()
                       GoOutCaravanMaguuma_MajestysRest()
                       If GetMapID() <> $MajestysRest_Map Then
                               CurrentAction("Routing - on map " & GetMapID() & ", need MajestysRest (" & $MajestysRest_Map & ").")
                               Return
                       EndIf
               EndIf
       Else
               If GetMapID() <> $MajestysRest_Map And GetMapID() <> $MajestysRest_Outpost And GetMapID() <> $MajestysRest_Transit And GetMapID() <> $MajestysRest_Transit2 Then
                       _Vanquisher_ResetGoOutRouteProgress()
                       CurrentAction("Traveling to outpost for MajestysRest.")
                       TravelTo($MajestysRest_Outpost)
               EndIf

               If GetMapID() = $MajestysRest_Outpost Or GetMapID() = $MajestysRest_Transit Or GetMapID() = $MajestysRest_Transit2 Then
                       _Vanquisher_ApplyDifficulty()
                       GoOutCaravanMaguuma_MajestysRest()
                       If GetMapID() <> $MajestysRest_Map Then
                               CurrentAction("Routing - on map " & GetMapID() & ", need MajestysRest (" & $MajestysRest_Map & ").")
                               Return
                       EndIf
               EndIf
       EndIf

	If GetMapID() <> $MajestysRest_Map Then
		CurrentAction("MajestysRest route waiting - on map " & GetMapID() & ", need " & $MajestysRest_Map & ".")
		Return
	EndIf

	CurrentAction("Starting MajestysRest vanquish route.")


	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(21522, -3238)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(21779, 2461)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(22541, 4683)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(21272, 6143)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(21113, 4524)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(20256, 3604)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(18129, 2842)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(20319, 2048)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(18986, 937)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(20192, 1033)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(20129, -1760)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(18193, -269)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(16865, 420)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(16252, -1572)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(17470, -1816)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(14470, -1522)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(13929, -179)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(13789, 167)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(13383, 1318)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(12857, 1127)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(14042, 1574)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(13386, 1320)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(13783, 170)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(13925, -184)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(14467, -1528)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(15320, -4921)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(19111, -7402)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(15322, -4908)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(14287, -5855)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(13149, -2097)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(11484, -6221)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(8805, -3632)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(10805, -966)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(10709, 3128)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(12931, 4938)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(15534, 3509)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(16319, 1057)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(15541, 3507)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(18276, 5403)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(15542, 3517)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(12933, 4938)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(13397, 6362)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(11537, 7896)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(9509, 7662)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(7572, 6635)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(7780, 4373)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(9496, 5933)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(9535, 7677)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(7589, 6650)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(7797, 4379)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(7341, 1421)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(8809, -3599)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(7368, 1495)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(4757, 4572)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(2336, 1664)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-2741, -521)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-5523, 833)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-5316, -2823)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-8030, -1960)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-6194, -3179)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-9703, -4954)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-8470, -6348)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-10353, -6155)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-9691, -4930)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-11913, -5155)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-10456, -4250)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-11244, -2854)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-10907, -1180)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-8225, -1147)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-6721, 1585)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-9188, 5174)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-13314, 2000)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-11277, -543)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-13536, 1472)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-17144, -511)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-22539, 1049)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-23160, 337)

	; reverse
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-23160, 337)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-22539, 1049)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-17144, -511)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-13536, 1472)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-11277, -543)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-13314, 2000)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-9188, 5174)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-6721, 1585)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-8225, -1147)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-10907, -1180)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-11244, -2854)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-10456, -4250)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-11913, -5155)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-9691, -4930)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-10353, -6155)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-8470, -6348)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-9703, -4954)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-6194, -3179)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-8030, -1960)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-5316, -2823)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-5523, 833)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-2741, -521)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(2336, 1664)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(4757, 4572)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(7368, 1495)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(8809, -3599)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(7341, 1421)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(7797, 4379)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(7589, 6650)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(9535, 7677)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(9496, 5933)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(7780, 4373)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(7572, 6635)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(9509, 7662)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(11537, 7896)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(13397, 6362)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(12933, 4938)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(15542, 3517)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(18276, 5403)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(15541, 3507)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(16319, 1057)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(15534, 3509)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(12931, 4938)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(10709, 3128)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(10805, -966)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(8805, -3632)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(11484, -6221)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(13149, -2097)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(14287, -5855)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(15322, -4908)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(19111, -7402)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(15320, -4921)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(14467, -1528)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(13925, -184)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(13783, 170)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(13386, 1320)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(14042, 1574)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(12857, 1127)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(13383, 1318)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(13789, 167)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(13929, -179)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(14470, -1522)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(17470, -1816)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(16252, -1572)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(16865, 420)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(18193, -269)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(20129, -1760)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(20192, 1033)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(18986, 937)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(20319, 2048)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(18129, 2842)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(20256, 3604)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(21113, 4524)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(21272, 6143)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(22541, 4683)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(21779, 2461)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(21522, -3238)
EndFunc
