Func GoOutCaravanAscalon_ScoundrelsRise()
        _Vanquisher_RunDynamicCaravanGoOut($ScoundrelsRise_Map, "ScoundrelsRise")
EndFunc

Func VQCaravanAscalon_ScoundrelsRise()
	If GetMapID() <> $ScoundrelsRise_Map And GetMapID() <> $ScoundrelsRise_Outpost Then
		_Vanquisher_ResetGoOutRouteProgress()
		CurrentAction("Traveling to outpost for ScoundrelsRise.")
		TravelTo($ScoundrelsRise_Outpost)
	EndIf

	If GetMapID() = $ScoundrelsRise_Outpost Then
		_Vanquisher_ApplyDifficulty()
		GoOutCaravanAscalon_ScoundrelsRise()
		If GetMapID() <> $ScoundrelsRise_Map Then
			CurrentAction("Routing - on map " & GetMapID() & ", need ScoundrelsRise (" & $ScoundrelsRise_Map & ").")
			Return
	EndIf
	EndIf

	If GetMapID() <> $ScoundrelsRise_Map Then
		CurrentAction("ScoundrelsRise route waiting - on map " & GetMapID() & ", need " & $ScoundrelsRise_Map & ".")
		Return
	EndIf

	CurrentAction("Starting ScoundrelsRise vanquish route.")


	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-2529, -5002)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-470, -2966)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(2763, -2033)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(4006, -1526)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(4030, -1364)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(4333, -1079)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(5013, -591)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(4648, -167)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(3978, 494)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(2655, 1441)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(2199, 2371)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(2159, 2464)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(2892, 2837)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(3772, 3968)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(3751, 4621)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(5106, 4888)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(6761, 4999)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(7683, 6114)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(6914, 7092)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(6540, 7500)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(4766, 8885)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(4359, 8553)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(3501, 7961)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(2428, 5685)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(2327, 5658)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(791, 5064)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-37, 6023)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-672, 7194)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-2283, 7737)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-4571, 8588)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-5158, 8757)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-5737, 9153)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-3183, 8086)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-2535, 6465)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-2394, 5688)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-3686, 4096)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-4695, 2122)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-5057, 416)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-3522, 4099)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-2551, 5576)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-668, 4943)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(1202, 3009)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(5940, 1835)

	; reverse
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(5940, 1835)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(1202, 3009)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-668, 4943)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-2551, 5576)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-3522, 4099)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-5057, 416)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-4695, 2122)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-3686, 4096)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-2394, 5688)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-2535, 6465)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-3183, 8086)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-5737, 9153)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-5158, 8757)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-4571, 8588)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-2283, 7737)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-672, 7194)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-37, 6023)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(791, 5064)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(2327, 5658)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(2428, 5685)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(3501, 7961)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(4359, 8553)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(4766, 8885)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(6540, 7500)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(6914, 7092)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(7683, 6114)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(6761, 4999)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(5106, 4888)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(3751, 4621)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(3772, 3968)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(2892, 2837)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(2159, 2464)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(2199, 2371)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(2655, 1441)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(3978, 494)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(4648, -167)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(5013, -591)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(4333, -1079)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(4030, -1364)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(4006, -1526)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(2763, -2033)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-470, -2966)
	If _Vanquisher_ShouldRunCaravanWaypoint() Then AggroMoveTo(-2529, -5002)
EndFunc

